### PR TITLE
ZMNHOD1 Cleanup

### PR DESCRIPTION
**Pull request by clandmeter**
This cleans up or removes the following:

* onoff cap: removed as it makes no sense in a shutter.
* meter_power: removed as it doesnt seem to work.
* remove un-needed optional settings
* some other small clean-ups

### CODE REVIEW

**Comment by RobinBol** [comment]
Hi, sorry for the delays. I would merge this PR but there are a few things to be done first. Could you please resolve the merge conflicts, sign the CLA, and explain to me the difference between this PR and https://github.com/athombv/com.qubino/pull/10, they seem to have overlapping changes?

**Comment by clandmeter** [comment]
Did you make progress on https://github.com/athombv/homey/issues/1317#issuecomment-287067832
Else it does make any sense for me to spend time on it.

**Comment by RobinBol** [comment]
There is no progress to be made by us, as Emile mentioned in that thread some of the Qubino modules are not Z-Wave certified yet, which means they may or may not work with our certified controller. If we have a certified module, which is not working we could take a look at it.

**Comment by clandmeter** [comment]
Sorry I'm not following.

1. You mention somewhere you will not support this type of module (i think it was all qubino shutter modules see #13) as they have issues, has this changed now?
2. What is this zwave certification you are talking about? Which modules are actually certified? I guess without that knowledge you should not support this product or you will end up with unhappy customers (just like the issue I mentioned)?

**Comment by RobinBol** [comment]
1. We will support it when Qubino gets their certification in order.
2. All devices carrying the Z-Wave logo have been certified to comply with the Z-Wave standard, the shutters have not (as can be read here: https://github.com/athombv/homey/issues/1317#issuecomment-287067832), which means they may or may not work (it seems to be a work in progress for Qubino).

We currently do not support the shutters (they are not in the app store version of this app), which will remain as long as they are not certified, as we can not guarantee they will work for everyone.

**Comment by clandmeter** [comment]
> We currently do not support the shutters (they are not in the app store version of this app), which will remain as long as they are not certified, as we can not guarantee they will work for everyone.

Then why do you want to merge this PR? this is a shutter device.

**Comment by RobinBol** [comment]
Well, the PR is still open so I had to either close or merge it. But if you are ok with it, I'll close the shutter related PRs until certified units are available.

**Comment by clandmeter** [comment]
I'm sorry Robin, but this conversation makes no sense to me at all.

Do whatever you want with it.

**Comment by RobinBol** [comment]
Ok, sorry for the confusion.

Summary, roller shutter support will be added once these modules are Z-Wave certified! For now I will close these PRs.

**Comment by jolny** [comment]
Hi @RobinBol !
The module is now certified: https://products.z-wavealliance.org/products/2536
Anything else you need to add support? :)

**Comment by Merlinuf** [comment]
Hi gents, can someone please add the shutter now when its certified ?

**Comment by Merlinuf** [comment]
So noone is working on this anymore

**Pull request closed without merging**
