### PR TITLE
Add ZMNHOD1 shutter DC support

### PR DESCRIPTION
**Pull request by clandmeter**
I'm trying to add a shutter driver for ZMNHOD1. I can add this device correctly and afterwards im able to calibrate it correctly from the settings page. Because of the lack of documentation I'm unable to find the correct settings on how to make this driver work properly (most of the driver is a simple copy and paste from other drivers).

What works/does not work

1. The up and down commands work as expected.
2. The on/off command also works correctly (similar like 1).
3. The idle (stop) command does not seem to work. I copied this from the fibaro module and its has some logic which inverts the direction command to stop the shutter but for qubino this does really invert the direction and does not stop until at the end.
4. The dim function (Slider) seems to work nicely except after the blind reaches its position the slider is not updated and returns back to its original position. It seems that the correct value is returned in Value (Raw) in hex. Not sure how to properly use that. (see output below)
5. the measure_power cap is only showing a factor 10, the result shows an in hex which translates into 20 dec but in the interface it shows just 2.0 (see example below)
6. the meter_power does not return any value in the interface. I have no clue about this.
7. I am unable to test measure_temperature (i have no temp module) but ive added it as I guess this should be generic for most qubino modules.
8. There are other advance settings like venetian blinds (parameter 71) which use "Endpoint 2" but I have no clue currently how to add support for this (I did add it to the settings to enable it).
9. The optional and debug settings should be removed if somebody wants to merge this.

Dimmer return:

```javascript
[debug] node.CommandClass['COMMAND_CLASS_SWITCH_MULTILEVEL'].on('report') arguments: { '0': { value: 3, name: 'SWITCH_MULTILEVEL_REPORT' },
  '1': { 'Value (Raw)': <Buffer 30>, Value: {} },
  '2': null }
```

Power measure:

```javascript
[debug] node.CommandClass['COMMAND_CLASS_METER'].on('report') arguments: { '0': { value: 2, name: 'METER_REPORT' },
  '1':
   { 'Properties1 (Raw)': <Buffer 21>,
     Properties1:
      { 'Scale bit 2': false,
        'Meter Type': 'Electric meter',
        'Rate Type': 'Import',
        'Meter Type (Parsed)': [Object],
        'Rate Type (Parsed)': [Object] },
     'Properties2 (Raw)': <Buffer 34>,
     Properties2: { Size: 4, 'Scale bits 10': 2, Precision: 1 },
     'Meter Value': <Buffer 00 00 00 14>,
     'Delta Time (Raw)': <Buffer 00 00>,
     'Delta Time': 0,
     'Previous Meter Value': <Buffer 00 00 00 00 00 00 00>,
     'Scale 2 (Raw)': <Buffer 00>,
     'Scale 2': 0,
     'Meter Value (Parsed)': 2,
     'Previous Meter Value (Parsed)': 0 },
  '2': null }
```

### CODE REVIEW

**Comment by clandmeter** [comment]
Some fixes:

1. It seems the power reporting of ~ 2 Watt is normal for this type of blind motor. 
2. I fixed the meter power with one of the recent commits
3. The Dimmer slider seems to change according to new setting
4. still cant test measure_temperature and venetian blinds.
5. The IDLE function of windowcoverings_state still doesnt work. @RobinBol any clue about this one?
6. added a nice svg icon for blinds (credits in the commit msg)

Is this ok to merge?

**Comment by RobinBol** [comment]
Hi! Thanks for the PR, much appreciated. You mentioned that you copied the settings from other modules. But this is very dangerous, the chance that some might not work or break something is present. Please see this page: http://qubino.com/products/flush-shutter-dc/, at the bottom there is a 'Additional parameters for pros' section with a button that shows the most important settings. Besides, in the (paper) device manual there is a lot to be found as well.

**Comment by clandmeter** [comment]
Hi @RobinBol 

With settings im mean driver logic (the cc part). All the actual settings have been manually added to the app.json and driver.js files by me. Not sure its complete/correct to be merged or not?

**Comment by RobinBol** [comment]
Oke great! Well it is definitely a great start, this device was already on my to do list to add. So in the coming weeks I will test your PR and extend/fix it where necessary!

**Pull request merged**
